# Binary closing with scipy

In [ ]:
import numpy as np
import piplite
await piplite.install("itkwidgets==1.0a7")
await piplite.install("pandas")
await piplite.install("scipy")
import pandas as pd
import scipy
import random

In [ ]:
from scipy import ndimage
from itkwidgets import view

In [ ]:
a = np.zeros((5,5), dtype=int)
a[1:-1, 1:-1] = 1; a[2,2] = 0
view(a)

### Closing removes small holes

In [9]:
view(ndimage.binary_closing(a).astype(int))

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

### Closing is the erosion of the dilation of the input

In [11]:
view(ndimage.binary_dilation(a).astype(int))


array([[0, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 1, 1, 0]])

In [12]:

 view(ndimage.binary_erosion(ndimage.binary_dilation(a)).astype(int))

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])